- name: (CentOS 8) Install EPEL & ELRepo repository
  yum:
    name:
     - epel-release
     - elrepo-release
    update_cache: yes

- name: (CentOS 8) Ensure WireGuard DKMS package is removed
  yum:
    name:
      - "wireguard-dkms"
    state: absent
  tags:
    - wg-install

- name: (CentOS 8) Install WireGuard packages
  yum:
    name:
      - "kmod-wireguard"
      - "wireguard-tools"
    state: present
  tags:
    - wg-install
